### ISSUE TITLE
It won't build on FreeBSD 10.1 Release

### ISSUE THREAD

**Issue by NuLL3rr0r** [timfel/krb5-auth#5]
# gem install timfel-krb5-auth -v '0.8'

Building native extensions.  This could take a while...
ERROR:  Error installing timfel-krb5-auth:
        ERROR: Failed to build gem native extension.

        /usr/local/bin/ruby20 extconf.rb
checking for main() in -lc... yes
checking for krb5_init_context() in -lkrb5... yes
creating Makefile

make "DESTDIR="
compiling ruby_krb5_auth.c
ruby_krb5_auth.c:54:35: warning: implicit declaration of function 'error_message' is invalid in C99 [-Wimplicit-function-declaration]
  rb_raise(cKrb5_Exception, "%s", error_message(error));
                                  ^
ruby_krb5_auth.c:54:35: warning: format specifies type 'char *' but the argument has type 'int' [-Wformat]
  rb_raise(cKrb5_Exception, "%s", error_message(error));
                             ~~   ^~~~~~~~~~~~~~~~~~~~
                             %d
ruby_krb5_auth.c:358:12: warning: 'krb5_change_password' is deprecated [-Wdeprecated-declarations]
  krbret = krb5_change_password(
           ^
/usr/include/krb5-protos.h:850:1: note: 'krb5_change_password' declared here
krb5_change_password (
^
ruby_krb5_auth.c:566:14: warning: implicit declaration of function 'krb5_decode_ticket' is invalid in C99 [-Wimplicit-function-declaration]
    krbret = krb5_decode_ticket(&creds.ticket, &tkt);
             ^
ruby_krb5_auth.c:579:52: error: no member named 'ticket_flags' in 'struct krb5_creds'
    rb_iv_set(line, "@ticket_flags", INT2NUM(creds.ticket_flags));
                                             ~~~~~ ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:580:52: error: no member named 'keyblock' in 'struct krb5_creds'
    rb_iv_set(line, "@cred_enctype", INT2NUM(creds.keyblock.enctype));
                                             ~~~~~ ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:581:53: error: no member named 'enc_part' in 'struct krb5_ticket'
    rb_iv_set(line, "@ticket_enctype", INT2NUM(tkt->enc_part.enctype));
                                               ~~~  ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:705:18: error: use of undeclared identifier 'TKT_FLG_FORWARDABLE'
  DEF_FLAG_CONST(TKT_FLG_FORWARDABLE);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:706:18: error: use of undeclared identifier 'TKT_FLG_FORWARDED'
  DEF_FLAG_CONST(TKT_FLG_FORWARDED);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:707:18: error: use of undeclared identifier 'TKT_FLG_PROXIABLE'
  DEF_FLAG_CONST(TKT_FLG_PROXIABLE);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:708:18: error: use of undeclared identifier 'TKT_FLG_PROXY'
  DEF_FLAG_CONST(TKT_FLG_PROXY);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:709:18: error: use of undeclared identifier 'TKT_FLG_MAY_POSTDATE'
  DEF_FLAG_CONST(TKT_FLG_MAY_POSTDATE);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:710:18: error: use of undeclared identifier 'TKT_FLG_POSTDATED'
  DEF_FLAG_CONST(TKT_FLG_POSTDATED);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:711:18: error: use of undeclared identifier 'TKT_FLG_INVALID'
  DEF_FLAG_CONST(TKT_FLG_INVALID);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:712:18: error: use of undeclared identifier 'TKT_FLG_RENEWABLE'
  DEF_FLAG_CONST(TKT_FLG_RENEWABLE);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:713:18: error: use of undeclared identifier 'TKT_FLG_INITIAL'
  DEF_FLAG_CONST(TKT_FLG_INITIAL);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:714:18: error: use of undeclared identifier 'TKT_FLG_HW_AUTH'
  DEF_FLAG_CONST(TKT_FLG_HW_AUTH);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:715:18: error: use of undeclared identifier 'TKT_FLG_PRE_AUTH'
  DEF_FLAG_CONST(TKT_FLG_PRE_AUTH);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:716:18: error: use of undeclared identifier 'TKT_FLG_TRANSIT_POLICY_CHECKED'
  DEF_FLAG_CONST(TKT_FLG_TRANSIT_POLICY_CHECKED);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:717:18: error: use of undeclared identifier 'TKT_FLG_OK_AS_DELEGATE'
  DEF_FLAG_CONST(TKT_FLG_OK_AS_DELEGATE);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:718:18: error: use of undeclared identifier 'TKT_FLG_ANONYMOUS'
  DEF_FLAG_CONST(TKT_FLG_ANONYMOUS);
                 ^
ruby_krb5_auth.c:703:41: note: expanded from macro 'DEF_FLAG_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:729:17: error: use of undeclared identifier 'ENCTYPE_DES_CBC_RAW'
  DEF_ENC_CONST(ENCTYPE_DES_CBC_RAW);
                ^
ruby_krb5_auth.c:723:41: note: expanded from macro 'DEF_ENC_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
ruby_krb5_auth.c:730:17: error: use of undeclared identifier 'ENCTYPE_DES3_CBC_SHA'; did you mean 'ENCTYPE_DES3_CBC_SHA1'?
  DEF_ENC_CONST(ENCTYPE_DES3_CBC_SHA);
                ^~~~~~~~~~~~~~~~~~~~
                ENCTYPE_DES3_CBC_SHA1
ruby_krb5_auth.c:723:41: note: expanded from macro 'DEF_ENC_CONST'
  rb_define_const(cCred, #name, INT2NUM(name))
                                        ^
/usr/local/include/ruby-2.0/ruby/ruby.h:1178:38: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) rb_int2num_inline(x)
                                     ^
/usr/include/krb5.h:130:5: note: 'ENCTYPE_DES3_CBC_SHA1' declared here
    ENCTYPE_DES3_CBC_SHA1       = KRB5_ENCTYPE_DES3_CBC_SHA1,
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.
*** Error code 1

Stop.
make: stopped in /usr/local/lib/ruby/gems/2.0/gems/timfel-krb5-auth-0.8/ext


Gem files will remain installed in /usr/local/lib/ruby/gems/2.0/gems/timfel-krb5-auth-0.8 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.0/gems/timfel-krb5-auth-0.8/ext/gem_make.out

**Comment by jedediahfrey** [comment]
Also fails on FreeNAS 9.3 (inside of a normal jail) with that same message (how I found it here).

I got around it by installing pam_krb5 and krb5 from pkg.

```
krb5-1.13                      Authentication system developed at MIT, successor to Kerberos IV
pam_krb5-4.6_2                 Pluggable Authentication Module for Kerberos 5
````

**Comment by NuLL3rr0r** [comment]
@ jedediahfrey Thank you so much for the fix! Now I can upgrade my GitLab installation happily :)

**Comment by nvx** [comment]
Only krb5 seems to be needed. I was able to fix this issue without needing to install pam_krb5.

FreeBSD 10.1 jail for GitLab also. :)

**Comment by NuLL3rr0r** [comment]
@nvx Thanks for the tip. I also did the gem installation without pam_krb5 again, and it seemed to work ;)
It seems this is not a bug, since they mentioned it here https://github.com/gitlabhq/gitlabhq/blob/7-6-stable/doc/update/7.5-to-7.6.md and I was reckless that I missed it.

**Comment by nvx** [comment]
@NuLL3rr0r 
Hmm it's missing from https://github.com/gitlabhq/gitlabhq/blob/7-6-stable/doc/update/6.x-or-7.x-to-7.6.md
Probably worth taking this ticket over there and closing this ticket as we've derailed a fair bit now and it's not an issue with krb5-auth at all.

**Comment by NuLL3rr0r** [comment]
Yep it makes sense. I created a pull request.

**Comment by NuLL3rr0r** [comment]
Now GitLab depends on version 0.8.3 of timfel-krb5-auth directly and it fails to build version 0.8 was fine. So, I had to reopen this.

gem install timfel-krb5-auth -v '0.8.3'

Building native extensions.  This could take a while...
ERROR:  Error installing timfel-krb5-auth:
    ERROR: Failed to build gem native extension.

```
    /usr/local/bin/ruby20 extconf.rb
```

checking for main() in -lc... yes
checking for krb5_init_context() in -lkrb5... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/bin/ruby20
    --with-krb5_auth-dir
    --without-krb5_auth-dir
    --with-krb5_auth-include
    --without-krb5_auth-include=${krb5_auth-dir}/include
    --with-krb5_auth-lib
    --without-krb5_auth-lib=${krb5_auth-dir}/
    --with-clib
    --without-clib
    --with-krb5lib
    --without-krb5lib
extconf.rb:7:in `<main>': Cannot find krb5 library (RuntimeError)

Gem files will remain installed in /usr/local/lib/ruby/gems/2.0/gems/timfel-krb5-auth-0.8.3 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.0/gems/timfel-krb5-auth-0.8.3/ext/gem_make.out

And this is the output from mkmf.log

have_library: checking for main() in -lc... -------------------- yes

"cc -o conftest -I/usr/local/include/ruby-2.0//amd64-freebsd10 -I/usr/local/include/ruby-2.0//ruby/backward -I/usr/local/include/ruby-2.0/ -I. -I/usr/local/include    -O3 -fno-fast-math -fno-omit-frame-pointer -O2 -pipe -march=core2  -fstack-protector -fno-strict-aliasing -fPIC conftest.c  -L. -L/usr/local/lib -L.  -Wl,-rpath,/usr/lib:/usr/local/lib -fstack-protector -rdynamic     -lruby20  -lexecinfo -lcrypt -lm -L/usr/local/lib -pthread  -lc"
checked program was:
/\* begin _/
1: #include "ruby.h"
2: 
3: int main(int argc, char *_argv)
4: {
5:   return 0;
6: }
/\* end */

"cc -o conftest -I/usr/local/include/ruby-2.0//amd64-freebsd10 -I/usr/local/include/ruby-2.0//ruby/backward -I/usr/local/include/ruby-2.0/ -I. -I/usr/local/include    -O3 -fno-fast-math -fno-omit-frame-pointer -O2 -pipe -march=core2  -fstack-protector -fno-strict-aliasing -fPIC conftest.c  -L. -L/usr/local/lib -L.  -Wl,-rpath,/usr/lib:/usr/local/lib -fstack-protector -rdynamic     -lruby20 -lc  -lexecinfo -lcrypt -lm -L/usr/local/lib -pthread  -lc"
conftest.c:5:57: error: use of undeclared identifier 'main'
int t(void) { void ((_volatile p)()); p = (void ((_)()))main; return 0; }
                                                        ^
1 error generated.
checked program was:
/\* begin _/
 1: #include "ruby.h"
 2: 
 3: /_top_/
 4: extern int t(void);
 5: int t(void) { void ((_volatile p)()); p = (void ((_)()))main; return 0; }
 6: int main(int argc, char *_argv)
 7: {
 8:   if (argc > 1000000) {
 9:     printf("%p", &t);
10:   }
11: 
12:   return 0;
13: }
/\* end */

"cc -o conftest -I/usr/local/include/ruby-2.0//amd64-freebsd10 -I/usr/local/include/ruby-2.0//ruby/backward -I/usr/local/include/ruby-2.0/ -I. -I/usr/local/include    -O3 -fno-fast-math -fno-omit-frame-pointer -O2 -pipe -march=core2  -fstack-protector -fno-strict-aliasing -fPIC conftest.c  -L. -L/usr/local/lib -L.  -Wl,-rpath,/usr/lib:/usr/local/lib -fstack-protector -rdynamic     -lruby20 -lc  -lexecinfo -lcrypt -lm -L/usr/local/lib -pthread  -lc"
conftest.c:5:15: warning: implicit declaration of function 'main' is invalid in C99 [-Wimplicit-function-declaration]
int t(void) { main(); return 0; }
              ^
1 warning generated.
checked program was:
/\* begin _/
 1: #include "ruby.h"
 2: 
 3: /_top_/
 4: extern int t(void);
 5: int t(void) { main(); return 0; }
 6: int main(int argc, char *_argv)
 7: {
 8:   if (argc > 1000000) {
 9:     printf("%p", &t);
10:   }
11: 
12:   return 0;
13: }
/\* end */

---

have_library: checking for krb5_init_context() in -lkrb5... -------------------- no

"cc -o conftest -I/usr/local/include/ruby-2.0//amd64-freebsd10 -I/usr/local/include/ruby-2.0//ruby/backward -I/usr/local/include/ruby-2.0/ -I. -I/usr/local/include    -O3 -fno-fast-math -fno-omit-frame-pointer -O2 -pipe -march=core2  -fstack-protector -fno-strict-aliasing -fPIC conftest.c  -L. -L/usr/local/lib -L.  -Wl,-rpath,/usr/lib:/usr/local/lib -fstack-protector -rdynamic    -lc  -lruby20 -lkrb5 -lc  -lexecinfo -lcrypt -lm -L/usr/local/lib -pthread  -lc"
conftest.c:5:57: error: use of undeclared identifier 'krb5_init_context'
int t(void) { void ((_volatile p)()); p = (void ((_)()))krb5_init_context; return 0; }
                                                        ^
1 error generated.
checked program was:
/\* begin _/
 1: #include "ruby.h"
 2: 
 3: /_top_/
 4: extern int t(void);
 5: int t(void) { void ((_volatile p)()); p = (void ((_)()))krb5_init_context; return 0; }
 6: int main(int argc, char *_argv)
 7: {
 8:   if (argc > 1000000) {
 9:     printf("%p", &t);
10:   }
11: 
12:   return 0;
13: }
/\* end */

"cc -o conftest -I/usr/local/include/ruby-2.0//amd64-freebsd10 -I/usr/local/include/ruby-2.0//ruby/backward -I/usr/local/include/ruby-2.0/ -I. -I/usr/local/include    -O3 -fno-fast-math -fno-omit-frame-pointer -O2 -pipe -march=core2  -fstack-protector -fno-strict-aliasing -fPIC conftest.c  -L. -L/usr/local/lib -L.  -Wl,-rpath,/usr/lib:/usr/local/lib -fstack-protector -rdynamic    -lc  -lruby20 -lkrb5 -lc  -lexecinfo -lcrypt -lm -L/usr/local/lib -pthread  -lc"
conftest.c:5:15: warning: implicit declaration of function 'krb5_init_context' is invalid in C99 [-Wimplicit-function-declaration]
int t(void) { krb5_init_context(); return 0; }
              ^
1 warning generated.
/usr/local/lib/libkrb5.so: undefined reference to `add_error_table'
/usr/local/lib/libkrb5.so: undefined reference to`remove_error_table'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/\* begin _/
 1: #include "ruby.h"
 2: 
 3: /_top_/
 4: extern int t(void);
 5: int t(void) { krb5_init_context(); return 0; }
 6: int main(int argc, char *_argv)
 7: {
 8:   if (argc > 1000000) {
 9:     printf("%p", &t);
10:   }
11: 
12:   return 0;
13: }
/\* end */

---

**Comment by nbyouri** [comment]
I "fixed" it by commenting the krb5_init_context check:

```
diff --git a/ext/extconf.rb b/ext/extconf.rb
index cc64cfe..6bde982 100644
--- a/ext/extconf.rb
+++ b/ext/extconf.rb
@@ -4,7 +4,7 @@ RbConfig::MAKEFILE_CONFIG['CC'] = ENV['CC'] if ENV['CC']
 extension_name = 'krb5_auth'
 dir_config(extension_name)
 have_library("c", "main")
-raise "Cannot find krb5 library" unless have_library("krb5","krb5_init_context")
+#raise "Cannot find krb5 library" unless have_library("krb5","krb5_init_context")
 raise "Cannot find krb5 headers" unless have_header("krb5.h")
 have_library("com_err","error_message")
 have_header("com_err.h")
```

Then I set the gem path variables

$ export GEM_HOME="$HOME/gitlab/vendor/bundle/ruby/2.0"
$ export GEM_PATH="$GEM_HOME:/gems"
$ rake gem

I'm running gitlab 7.8 no 10.1-RELEASE-p6 now :)
$ gem install pkg/timfel-krb5-auth-0.8.3.gem

**Comment by vanoinfo** [comment]
try to move to krb5-111-1.11.6 http://svnweb.freebsd.org/ports/head/security/krb5-111/

**Comment by NuLL3rr0r** [comment]
Thanks @yrmt I have to find some spare time and try it.

**Comment by deees** [comment]
`krb5-111` worked for me, thanks.

**Comment by hasufell** [comment]
> krb5-111 worked for me, thanks.

works

**Comment by NuLL3rr0r** [comment]
@vanoinfo thank you so much! I did an upgrade on two of my instances and both krb5-111 and krb-112 did the trick. But I believe this is a bug since krb5-auth won't build with newer krb5 1.13.

**Comment by krisklosterman** [comment]
This is still an issue. How do I upgrade to the krb5-111 so that I can build and install this? I am on Debian though not FreeBSD.

**Comment by makr8100** [comment]
I came across this issue with openSUSE 13.2, turns out it was only caused by missing krb5-devel (krb5-dev for you Debian-ish users).

**Comment by ed006949** [comment]
helped - pkg install rubygem-timfel-krb5-auth
