### ISSUE TITLE
It won't build with mit-krb5-1.13

### ISSUE THREAD

**Issue by miramir** [timfel/krb5-auth#9]
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby21 -r ./siteconf20150104-16676-1moq2e9.rb extconf.rb 
checking for main() in -lc... yes

checking for krb5_init_context() in -lkrb5... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling ruby_krb5_auth.c
linking shared-object krb5_auth.so
ruby_krb5_auth.o: In function `Krb5_register_error':
ruby_krb5_auth.c:(.text+0x138): undefined reference to `error_message'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
Makefile:232: ошибка выполнения рецепта для цели «krb5_auth.so»
make: *** [krb5_auth.so] Ошибка 1

make failed, exit code 2

Gem files will remain installed in /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/timfel-krb5-auth-0.8 for inspection.
Results logged to /home/git/gitlab/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/timfel-krb5-auth-0.8/gem_make.out
An error occurred while installing timfel-krb5-auth (0.8), and Bundler cannot continue.
Make sure that `gem install timfel-krb5-auth -v '0.8'` succeeds before bundling.
```

**Comment by timfel** [comment]
Merged
